export const SITE_CONFIG = {
  name: 'Gemini Master',
  nameKo: 'Google Gemini AI 학습 플랫폼',
  description: 'Google Gemini AI의 모든 기능을 학습하는 종합 플랫폼',
  url: 'https://gemini.dreamitbiz.com',
  base: '/',
  author: 'DreamIT Biz',
  email: 'contact@dreamitbiz.com',
  github: 'https://github.com/aebonlee/gemini',
};

export const LEARNING_PATHS = [
  {
    id: 'gemini-models',
    icon: 'fa-gem',
    nameKo: 'Gemini 모델 가이드',
    nameEn: 'Gemini Model Guide',
    descKo: 'Gemini Flash, Pro, Ultra 모델의 특징과 활용법을 학습합니다.',
    descEn: 'Learn the features and usage of Gemini Flash, Pro, and Ultra models.',
    color: '#4285F4',
    path: '/gemini-models',
    topics: ['Flash', 'Pro', 'Ultra', '모델 선택', '토큰 & 가격', '컨텍스트 윈도우'],
  },
  {
    id: 'gemini-api',
    icon: 'fa-code',
    nameKo: 'Gemini API',
    nameEn: 'Gemini API',
    descKo: 'Google Gemini API를 활용한 애플리케이션 개발을 학습합니다.',
    descEn: 'Learn application development with the Google Gemini API.',
    color: '#EA4335',
    path: '/gemini-api',
    topics: ['REST API', 'Python SDK', 'Node.js SDK', 'Streaming', 'Function Calling', '요금제'],
  },
  {
    id: 'google-ai-studio',
    icon: 'fa-flask',
    nameKo: 'Google AI Studio',
    nameEn: 'Google AI Studio',
    descKo: 'Google AI Studio에서 프롬프트 설계와 모델 테스트를 학습합니다.',
    descEn: 'Learn prompt design and model testing in Google AI Studio.',
    color: '#FBBC04',
    path: '/google-ai-studio',
    topics: ['프롬프트 설계', 'Structured Output', 'Tuning', 'API 키 관리', '모델 테스트'],
  },
  {
    id: 'vertex-ai',
    icon: 'fa-cloud',
    nameKo: 'Vertex AI',
    nameEn: 'Vertex AI',
    descKo: 'Google Cloud Vertex AI에서 Gemini를 엔터프라이즈 환경에서 활용합니다.',
    descEn: 'Use Gemini in enterprise environments with Google Cloud Vertex AI.',
    color: '#34A853',
    path: '/vertex-ai',
    topics: ['Vertex AI Studio', 'Model Garden', 'Grounding', 'RAG', '엔터프라이즈'],
  },
  {
    id: 'prompt-engineering',
    icon: 'fa-wand-magic-sparkles',
    nameKo: '프롬프트 엔지니어링',
    nameEn: 'Prompt Engineering',
    descKo: 'Gemini와 효과적으로 소통하는 프롬프트 작성법을 배웁니다.',
    descEn: 'Learn effective prompt writing techniques for Gemini.',
    color: '#E040FB',
    path: '/prompt-engineering',
    topics: ['기본 원칙', 'System Instructions', 'Few-shot', 'Chain of Thought', 'Safety Settings'],
  },
  {
    id: 'multimodal',
    icon: 'fa-images',
    nameKo: '멀티모달 AI',
    nameEn: 'Multimodal AI',
    descKo: 'Gemini의 텍스트, 이미지, 오디오, 비디오 멀티모달 기능을 학습합니다.',
    descEn: 'Learn Gemini\'s multimodal capabilities across text, image, audio, and video.',
    color: '#FF6D00',
    path: '/multimodal',
    topics: ['이미지 이해', '비디오 분석', '오디오 처리', 'PDF 분석', '이미지 생성'],
  },
  {
    id: 'model-comparison',
    icon: 'fa-chart-bar',
    nameKo: '모델 비교',
    nameEn: 'Model Comparison',
    descKo: 'Gemini 모델 패밀리의 성능, 가격, 용도를 비교합니다.',
    descEn: 'Compare performance, pricing, and use cases of the Gemini model family.',
    color: '#00BCD4',
    path: '/model-comparison',
    topics: ['Flash vs Pro', 'Ultra', '벤치마크', '가격 비교', '용도별 추천'],
  },
];
